version: "3"
services:
    app:
        labels:
            caddy: jot.mettle.run
            caddy.reverse_proxy: "{{upstreams 3000}}"
        networks:
            - reverse_proxy
networks:
    reverse_proxy:
        external:
            name: caddy-network
